const motivationalMessages = [
    "Seize the day!",
    "Every moment counts.",
    "Believe in yourself.",
    "You can do it!",
    "Every challenge is an opportunity.",
    "Dare to dream big.",
    "Hard work pays off.",
    "Stay positive.",
    "Never give up.",
    "Your potential is limitless.",
    "Chase your dreams.",
    "Stay dedicated.",
    "The world is yours.",
    "Stay hungry. Stay foolish.",
    "Mistakes are stepping stones to success.",
    "Every day is a fresh start.",
    "Keep pushing forward.",
    "You are capable of amazing things.",
    "You've got this!",
    "Opportunities are everywhere.",
    "Be your best self.",
    "Believe in the power of dreams.",
    "Stay focused and never settle.",
    "You can overcome any obstacle.",
    "You are stronger than you think.",
    "Passion is the key.",
    "Cherish every moment.",
    "Take the leap.",
    "The sky's the limit.",
    "You're unstoppable.",
    "Today is your day.",
    "Stay committed to your dreams.",
    "The future is bright.",
    "You are destined for greatness.",
    "Challenges make you stronger.",
    "You can change the world.",
    "Embrace every possibility.",
    "Your dreams are valid.",
    "Every effort counts.",
    "Success is a journey.",
    "Stay true to yourself.",
    "Trust the process.",
    "You can achieve anything.",
    "You are your only limit.",
    "Push your boundaries.",
    "Shine bright.",
    "Turn dreams into reality.",
    "Every setback is a setup for a comeback.",
    "Be relentless.",
    "Success starts with you.",
    "Believe in miracles.",
    "Always aim high.",
    "The best is yet to come.",
    "You're worth it.",
    "The universe believes in you.",
    "Stay brave.",
    "Climb higher.",
    "Dream. Believe. Achieve.",
    "You can move mountains.",
    "Consistency is key.",
    "Stay passionate.",
    "Let your dreams be your wings.",
    "Your time is now.",
    "It's a new dawn. It's a new day.",
    "Be a game changer.",
    "Exceed your own expectations.",
    "You were born to shine.",
    "Cherish the journey.",
    "Life is what you make it.",
    "Let passion lead the way.",
    "Hard times pass. Dreams stay.",
    "Find strength in adversity.",
    "Choose joy.",
    "Rise above challenges.",
    "Dreams don't work unless you do.",
    "You are unique and special.",
    "Your story is powerful.",
    "Be bold. Be brave. Be you.",
    "Make today count.",
    "The universe is cheering you on.",
    "You have a purpose.",
    "Believe in your vision.",
    "Achieve the impossible.",
    "Turn obstacles into opportunities.",
    "Today is a gift.",
    "Find beauty in the journey.",
    "Success is in the small steps.",
    "Stay driven.",
    "Be unstoppable.",
    "Your journey is worth it.",
    "Embrace change.",
    "Keep your eyes on the prize.",
    "Every dream is achievable.",
    "There's magic inside you.",
    "Your spirit is powerful.",
    "Take charge of your destiny.",
    "You have the power to create change.",
    "Your passion will lead you to success.",
    "Make every second count.",
    "Every mountain top is within reach.",
    "Dream big. Work hard. Stay humble."
];

// Test by logging a random message from the array

  const displayRandomMessage = () => {
        const randomIndex = Math.floor(Math.random() * motivationalMessages.length);
        const message = motivationalMessages[randomIndex];
        document.getElementById('motivational-message').innerText = message;
    }


